[package]
name = "c-trans"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vir = { path = "../verus/source/vir" }
lang-c = { path = "../lang-c" }
clap = { version = "4.5.4", features = ["derive"] }
